name: Build iOS Dylib

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies & Setup Theos
      run: |
        brew install ldid
        sudo mkdir -p /var/mobile/theos
        sudo chown -R $USER:staff /var/mobile/theos
        git clone --recursive https://github.com/theos/theos.git /var/mobile/theos

    - name: Patch and Prepare
      run: |
        touch x2nios.h
        find . -name "Makefile" -exec sed -i '' 's/-Werror//g' {} +
        find . -name "*.mk" -exec sed -i '' 's/-Werror//g' {} +

    - name: Build
      run: |
        export ADDITIONAL_CFLAGS="-w"
        export ADDITIONAL_OBJCFLAGS="-w"
        make

    - name: Collect Dylib Files
      run: |
        # Tạo một thư mục ngoài sáng để gom hàng
        mkdir -p output_dylibs
        # Quét mọi ngóc ngách (kể cả thư mục ẩn .theos) và lôi file .dylib ra ngoài
        find . -name "*.dylib" -type f -exec cp {} output_dylibs/ \;
        # In ra danh sách file để dễ kiểm tra trong log
        echo "Đã gom được các file sau:"
        ls -la output_dylibs/

    - name: Upload Dylib Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ModMenu-Dylib
        path: output_dylibs/*.dylib
