- name: Install Dependencies & Setup Theos
      run: |
        brew untap aws/tap || true  # Thêm dòng này để dọn dẹp lỗi Homebrew
        brew install ldid
        sudo mkdir -p /var/mobile/theos
        sudo chown -R $USER:staff /var/mobile/theos
        git clone --recursive https://github.com/theos/theos.git /var/mobile/theos

    - name: Patch and Prepare
      run: |
        touch x2nios.h
        find . -name "Makefile" -exec sed -i '' 's/-Werror//g' {} +
        find . -name "*.mk" -exec sed -i '' 's/-Werror//g' {} +

    - name: Build
      run: |
        export THEOS=/var/mobile/theos # BẮT BUỘC PHẢI THÊM DÒNG NÀY
        export ADDITIONAL_CFLAGS="-w"
        export ADDITIONAL_OBJCFLAGS="-w"
        make
